# syntax=docker/dockerfile:1

FROM node:22-alpine AS builder

RUN npm install -g pnpm@latest-10

WORKDIR /frontend

COPY ./ ./

RUN pnpm install --frozen-lockfile \
    && pnpm run build

FROM nginx:latest

WORKDIR /usr/share/nginx/html

# Copy the built app
COPY --from=builder /frontend/dist .

# Copy custom Nginx configuration to handle SPA routing
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
