# syntax=docker/dockerfile:1

FROM node:22-alpine AS builder

RUN npm install -g pnpm@latest-10

WORKDIR /frontend

COPY ./ ./

ARG VITE_ENABLE_BID=true
ARG VITE_ENABLE_AUTH=true

ENV VITE_ENABLE_BID=${VITE_ENABLE_BID}
ENV VITE_ENABLE_AUTH=${VITE_ENABLE_AUTH}

RUN pnpm install --frozen-lockfile \
    && pnpm run build

FROM nginx:latest

WORKDIR /usr/share/nginx/html

COPY --from=builder /frontend/dist .

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
