name: koentjoro
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    networks:
      - frontend
    ports:
      - "5173:5173"
    command: ["pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "5173"]
    volumes:
      - ./frontend:/frontend:cached
      - frontend_node_modules:/frontend/node_modules
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5173/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongodb/mongodb-community-server:8.0.15-ubuntu2204
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mongosh --quiet --eval "db.adminCommand({ ping: 1 })" -u $$MONGODB_INITDB_ROOT_USERNAME -p $$MONGODB_INITDB_ROOT_PASSWORD --authenticationDatabase admin || mongo --quiet --eval "db.adminCommand({ ping: 1 })" -u $$MONGODB_INITDB_ROOT_USERNAME -p $$MONGODB_INITDB_ROOT_PASSWORD --authenticationDatabase admin || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mongodb_data:
  frontend_node_modules:

networks:
  backend:
  frontend:
