name: koentjoro
services:
  backend:
    build:
      context: ./backend-python
      dockerfile: ./docker/dockerfile
    networks:
      - backend
      - shared_proxy_network
    env_file:
      - ./backend-python/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-service-account.json
    volumes:
      - ./backend-python/firebase-service-account.json:/app/firebase-service-account.json:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.prod
    networks:
      - frontend
      - shared_proxy_network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  frontend_node_modules:

networks:
  backend:
  frontend:
  shared_proxy_network:
    external: true
