/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _appRouteImport } from './routes/__app'
import { Route as _appHomeIndexRouteImport } from './routes/__app/home/index'

const _appRoute = _appRouteImport.update({
  id: '/__app',
  getParentRoute: () => rootRouteImport,
} as any)
const _appHomeIndexRoute = _appHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => _appRoute,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof _appHomeIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof _appHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__app': typeof _appRouteWithChildren
  '/__app/home/': typeof _appHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/home'
  id: '__root__' | '/__app' | '/__app/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _appRoute: typeof _appRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__app': {
      id: '/__app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__app/home/': {
      id: '/__app/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof _appHomeIndexRouteImport
      parentRoute: typeof _appRoute
    }
  }
}

interface _appRouteChildren {
  _appHomeIndexRoute: typeof _appHomeIndexRoute
}

const _appRouteChildren: _appRouteChildren = {
  _appHomeIndexRoute: _appHomeIndexRoute,
}

const _appRouteWithChildren = _appRoute._addFileChildren(_appRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _appRoute: _appRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
